name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# set default permission to readonly
permissions: read-all

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      # Install git and unzip, as not installed on self-hosted runner images
      #- name: Install Git
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y git unzip
      # Checkout code from repository
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      # Install JDK
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Setup Android for self-hosted runners
      #- name: Setup Android SDK
      #  uses: amyu/setup-android@v4
      - name: Build with Gradle
        run: ./gradlew build test sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
