name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

# set default permission to readonly
permissions: read-all

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      # Install git and unzip, as not installed on self-hosted runner images
      #- name: Install Git
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y git unzip
      # Checkout code from repository
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      # Install JDK
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Setup Android for self-hosted runners
      #- name: Setup Android SDK
      #  uses: amyu/setup-android@v4
      - name: Build with Gradle
        run: ./gradlew build test lint sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        # Atleast Developer Edition needed, right now only freeware version is used
        #-Dsonar.branch.name=${{ github.ref_name }}
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Build APK
        run: |
          ./gradlew assembleRelease
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      # Only runs, if a tag of a branch is created
      - name: Upload APK as GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        permissions:
          contents: write
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
