name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Setup unzip
      - name: Setup unzip
        run: |
          sudo apt install -y unzip

      # Setup Android for self-hosted runners
      - name: Setup Android SDK
        uses: amyu/setup-android@v4

      - name: Build with Gradle
        run: ./gradlew build
  sonarqube:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        with:
          projectBaseDir: /home/runner/_work/storageroom/storageroom
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
