name: Linting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linting:
    # configure permissions for Action
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    # run on self-hosted runners to be not dependent on free tier
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
          DEFAULT_WORKSPACE: /home/runner/_work/storageroom/storageroom
          USE_FIND_ALGORITHM: true
          VALIDATE_GO_RELEASER: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
