name: Linting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# set default permission to readonly
permissions: read-all

jobs:
  linting:
    # configure permissions for Action
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    # run on self-hosted runners to be not dependent on free tier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v7
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # disable java and kotlin linters, as SonarQube is used
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_JAVA: false
          VALIDATE_JSCPD: false
          VALIDATE_KOTLIN: false
